// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWsgH-nwr2C4Csg8FI-X7jhI4ZyrebxZU',
    appId: '1:802251373588:web:9ba94237c0e8dd28c97b01',
    messagingSenderId: '802251373588',
    projectId: 'asthma-app-b1e32',
    authDomain: 'asthma-app-b1e32.firebaseapp.com',
    storageBucket: 'asthma-app-b1e32.firebasestorage.app',
    measurementId: 'G-269CVLS02C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_x3nN3zAqepuKLGR4P166O1bqA2F9RE',
    appId: '1:802251373588:android:7b23f68f7efdad43c97b01',
    messagingSenderId: '802251373588',
    projectId: 'asthma-app-b1e32',
    storageBucket: 'asthma-app-b1e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD2Xds9w_N9TaR2S6bUb_3pe0WFuczS8I',
    appId: '1:802251373588:ios:ed31f90c45a86769c97b01',
    messagingSenderId: '802251373588',
    projectId: 'asthma-app-b1e32',
    storageBucket: 'asthma-app-b1e32.firebasestorage.app',
    androidClientId: '802251373588-2fg7anrainkt1rc68m0fqbhusvk8i42m.apps.googleusercontent.com',
    iosClientId: '802251373588-7iie0mpi1p0agvf5jam6nlnr56dsnad2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWsgH-nwr2C4Csg8FI-X7jhI4ZyrebxZU',
    appId: '1:802251373588:web:937bbd90c7b02224c97b01',
    messagingSenderId: '802251373588',
    projectId: 'asthma-app-b1e32',
    authDomain: 'asthma-app-b1e32.firebaseapp.com',
    storageBucket: 'asthma-app-b1e32.firebasestorage.app',
    measurementId: 'G-Y3HY2F449P',
  );

}